kind: Deployment
apiVersion: apps/v1
metadata:
    name: abctech-app
spec:
    replicas: 3
    minReadySeconds: 45
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 2
    selector:
        matchLabels:
            app: abctech-app
    template:
        metadata:
            labels:
                app: abctech-app
        spec:
            containers:
                - image: clong1969/abctech:56
                  name: app

kind: Service
apiVersion: v1
metadata:
    name: abctech-service
spec:
    type: NodePort
    selector:
        app: abctech-app
    ports:
        - port: 80 #cluster port
          targetPort: 8080 #container image port
